### ISSUE TITLE
After doubling a hard 12 and getting a 10, the hand was considered won instead of a bust

### ISSUE THREAD

**Issue by amitzohar42** [Mabbai/Card-Counting-Simulator#1]
Here's a photo: 
![photo](https://github.com/Mabbai/Card-Counting-Simulator/assets/47270176/74cfc664-e861-4b38-921b-f07d33d50dc2)

**Comment by Mabbai** [comment]
Thank you for noticing! By my surpise I forgot to add a bust filter for double-ups. Now it works properly, thanks again for telling!

//mabbai
